export const ADVISOR_IDS = Object.freeze({
  ANALYST: 'analyst',
  BUILDER: 'builder',
  MARKETER: 'marketer',
  NEGOTIATOR: 'negotiator',
  ENGINEER: 'engineer',
  BANKER: 'banker',
  FUTURIST: 'futurist',
  FIXER: 'fixer',
  ORACLE: 'oracle',
  SOVEREIGN: 'sovereign',
});

export const ADVISORS = Object.freeze([
  Object.freeze({
    id: ADVISOR_IDS.ANALYST,
    order: 1,
    name: 'Analyst',
    label: '\uBD84\uC11D\uAC00',
    themeColor: '#00FF41',
    unlock: '\uAE30\uBCF8 \uD574\uAE08',
    stats: Object.freeze({
      demandBonus: 0,
      costMultiplier: 1,
      qualityBonus: 0,
      creditBonus: 0,
      eventShieldChance: 0,
      rewardLuck: 0.02,
    }),
  }),
  Object.freeze({
    id: ADVISOR_IDS.BUILDER,
    order: 2,
    name: 'Builder',
    label: '\uC124\uBE44\uC7A5\uC778',
    themeColor: '#36D1DC',
    unlock: '5\uAC1C\uC6D4\uCC28 \uB3C4\uB2EC',
    stats: Object.freeze({
      demandBonus: 0,
      costMultiplier: 0.96,
      qualityBonus: 0.4,
      creditBonus: 0,
      eventShieldChance: 0,
      rewardLuck: 0,
    }),
  }),
  Object.freeze({
    id: ADVISOR_IDS.MARKETER,
    order: 3,
    name: 'Marketer',
    label: '\uB9C8\uCF00\uD130',
    themeColor: '#FFEA00',
    unlock: '10\uAC1C\uC6D4\uCC28 \uB3C4\uB2EC',
    stats: Object.freeze({
      demandBonus: 0.06,
      costMultiplier: 1.02,
      qualityBonus: 0,
      creditBonus: 0,
      eventShieldChance: 0,
      rewardLuck: 0.03,
    }),
  }),
  Object.freeze({
    id: ADVISOR_IDS.NEGOTIATOR,
    order: 4,
    name: 'Negotiator',
    label: '\uD611\uC0C1\uAC00',
    themeColor: '#FF8C42',
    unlock: '20\uAC1C\uC6D4\uCC28 \uB3C4\uB2EC',
    stats: Object.freeze({
      demandBonus: 0,
      costMultiplier: 0.98,
      qualityBonus: 0,
      creditBonus: 1,
      eventShieldChance: 0.04,
      rewardLuck: 0.01,
    }),
  }),
  Object.freeze({
    id: ADVISOR_IDS.ENGINEER,
    order: 5,
    name: 'Engineer',
    label: '\uC5D4\uC9C0\uB2C8\uC5B4',
    themeColor: '#8AFF80',
    unlock: '30\uAC1C\uC6D4\uCC28 \uB3C4\uB2EC',
    stats: Object.freeze({
      demandBonus: 0,
      costMultiplier: 0.93,
      qualityBonus: 0.8,
      creditBonus: 0,
      eventShieldChance: 0.02,
      rewardLuck: 0,
    }),
  }),
  Object.freeze({
    id: ADVISOR_IDS.BANKER,
    order: 6,
    name: 'Banker',
    label: '\uAE08\uC735\uC804\uBB38\uAC00',
    themeColor: '#B5FFFC',
    unlock: '40\uAC1C\uC6D4\uCC28 \uB3C4\uB2EC',
    stats: Object.freeze({
      demandBonus: 0,
      costMultiplier: 1,
      qualityBonus: 0,
      creditBonus: 2,
      eventShieldChance: 0,
      rewardLuck: 0.04,
    }),
  }),
  Object.freeze({
    id: ADVISOR_IDS.FUTURIST,
    order: 7,
    name: 'Futurist',
    label: '\uBBF8\uB798\uD559\uC790',
    themeColor: '#A78BFA',
    unlock: '60\uAC1C\uC6D4\uCC28 \uB3C4\uB2EC',
    stats: Object.freeze({
      demandBonus: 0.05,
      costMultiplier: 1,
      qualityBonus: 0.3,
      creditBonus: 0,
      eventShieldChance: 0.08,
      rewardLuck: 0.05,
    }),
  }),
  Object.freeze({
    id: ADVISOR_IDS.FIXER,
    order: 8,
    name: 'Fixer',
    label: '\uD574\uACB0\uC0AC',
    themeColor: '#FF4D6D',
    unlock: '80\uAC1C\uC6D4\uCC28 \uB3C4\uB2EC',
    stats: Object.freeze({
      demandBonus: 0.02,
      costMultiplier: 0.97,
      qualityBonus: 0,
      creditBonus: 1,
      eventShieldChance: 0.12,
      rewardLuck: 0,
    }),
  }),
  Object.freeze({
    id: ADVISOR_IDS.ORACLE,
    order: 9,
    name: 'Oracle',
    label: '\uC608\uCE21\uAC00',
    themeColor: '#00C2FF',
    unlock: '100\uAC1C\uC6D4\uCC28 \uB3C4\uB2EC',
    stats: Object.freeze({
      demandBonus: 0.07,
      costMultiplier: 1,
      qualityBonus: 0,
      creditBonus: 1,
      eventShieldChance: 0.1,
      rewardLuck: 0.08,
    }),
  }),
  Object.freeze({
    id: ADVISOR_IDS.SOVEREIGN,
    order: 10,
    name: 'Sovereign',
    label: '\uC18C\uBC84\uB9B0',
    themeColor: '#FFFFFF',
    unlock: '120\uAC1C\uC6D4 \uD074\uB9AC\uC5B4',
    stats: Object.freeze({
      demandBonus: 0.1,
      costMultiplier: 0.94,
      qualityBonus: 1,
      creditBonus: 2,
      eventShieldChance: 0.15,
      rewardLuck: 0.1,
    }),
  }),
]);
