export const INITIAL_STATS = Object.freeze({
  playtime: 0,
  profitTurns: 0,
  lossTurns: 0,
  maxShare: 0,
  bankruptcyCount: 0,
  externalEventCount: 0,
  rivalEventCount: 0,
  eventSuccessCount: 0,
  eventTotalCount: 0,
  rivalDominated: 0,
});

export const INITIAL_STATE = Object.freeze({
  floor: 1,
  health: 10,
  maxHealth: 10,
  momentum: 0,
  momentumHistory: Object.freeze([]),
  capital: 5000000,
  debt: 0,
  loans: Object.freeze([]),
  creditScore: 70,
  quality: 8,
  cost: 3000,
  orderCap: 1000,
  costReductionTotal: 0,
  factoryFailStreak: 0,
  costReductionFailStreak: 0,
  brand: 2,
  awareness: 10,
  econPhase: 'stable',
  rivals: Object.freeze([]),
  metRivals: Object.freeze([]),
  playerShareHistory: Object.freeze([]),
  activeEffects: Object.freeze([]),
  stats: INITIAL_STATS,
});
